# fly.toml file generated for rustplayground on 2022-05-21T20:34:49+09:00

app = "typerust"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
RUST_LOG = "info"
IP_ADDR = "0.0.0.0:8080"

[experimental]
allowed_public_ports = []
auto_rollback = true

[[services]]
http_checks = []
internal_port = 8080
processes = ["app"]
protocol = "tcp"
script_checks = []

[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"

[[services.ports]]
handlers = ["http"]
port = 80

[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
restart_limit = 0
timeout = "2s"
