# fly.toml file generated for rustplayground on 2022-05-21T20:34:49+09:00

app = "typerust"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
RUST_LOG = "info"
IP_ADDR = "0.0.0.0:8080"
OTLP_EXPORT_URL = "https://api.honeycomb.io:443"
LOCAL_LOG_ONLY = "false"

[experimental]
allowed_public_ports = []
auto_rollback = true

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 0
[http_service.concurrency]
type = "requests"
soft_limit = 200
hard_limit = 250
